theme: jekyll-theme-leap-day
title: Carlos Curty<img src="https://user-images.githubusercontent.com/68711113/165939619-bdc50df0-1ce6-4c17-a87a-e54a4e266666.png" width="100" align="left"> 
description: Meus projetos [GitHub Page]
